### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by ghost** [choijiho0021/react-native-textIndicator-sectionList-sidebar#2]
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 6550.9091796875, "dt": 1873, "prevDt": 1243}

**Comment by choijiho0021** [comment]
(https://legacy.reactjs.org/docs/optimizing-performance.html#virtualize-long-lists)

Warning provided by FlatList. Occurs when trying to provide too many items at once.
